Metrics/LineLength:
  Max: 120
Metrics/ClassLength:
  Max: 130
Metrics/MethodLength:
  Max: 20
Metrics/CyclomaticComplexity:
  Max: 15
Metrics/PerceivedComplexity:
  Max: 15
Metrics/AbcSize:
  Enabled: false
