Metrics/LineLength:
  Max: 120
Metrics/ClassLength:
  Max: 150
Metrics/MethodLength:
  Max: 30
Metrics/CyclomaticComplexity:
  Max: 15
Metrics/PerceivedComplexity:
  Max: 15
Metrics/AbcSize:
  Enabled: false
