Style/FrozenStringLiteralComment:
  Enabled: false
Metrics/LineLength:
  Max: 120
Style/Documentation:
  Enabled: false
Metrics/MethodLength:
  Max: 30
Style/AsciiComments:
  Enabled: false
Style/MutableConstant:
  Enabled: false
Style/BlockComments:
  Enabled: false
Metrics/ClassLength:
  Max: 130
Metrics/CyclomaticComplexity:
  Max: 20
Metrics/PerceivedComplexity:
  Max: 20
Style/ClassVars:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Lint/UselessAssignment:
  Enabled: false
